bpmn benchmark bug fixes execution feature
bug unclear:
java.lang.RuntimeException: Exception in step
	at jadex.execution.impl.ExecutionFeature.doRun(ExecutionFeature.java:696)
	at jadex.execution.impl.ExecutionFeature$ThreadRunner.run(ExecutionFeature.java:377)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:409)
	at java.base/java.util.Timer.schedule(Timer.java:205)
	at jadex.execution.impl.ExecutionFeature.waitForDelay(ExecutionFeature.java:254)
	at jadex.bpmn.runtime.handler.EventIntermediateTimerActivityHandler.doWait(EventIntermediateTimerActivityHandler.java:31)
	at jadex.bpmn.runtime.handler.AbstractEventIntermediateTimerActivityHandler.execute(AbstractEventIntermediateTimerActivityHandler.java:41)
	at jadex.bpmn.runtime.ExecuteProcessThread.accept(ExecuteProcessThread.java:77)
	at jadex.bpmn.runtime.ExecuteProcessThread.accept(ExecuteProcessThread.java:1)
	at jadex.execution.impl.ExecutionFeature.lambda$1(ExecutionFeature.java:134)
	at jadex.execution.impl.ExecutionFeature.doRun(ExecutionFeature.java:686)
	... 4 more